### PR TITLE
added sponsors section

### PR DESCRIPTION
**Pull request by immavalls**
A falta del Logo de Raquel Lainde, que alguien revise la nueva pagina principal, lista de sponsors y enlaces. He cambiado todos los logos por los que ha enviado cada uno, o eso espero.

### CODE REVIEW

**Comment by immavalls** [comment]
- I was using the incoming order. No problem, changed.
- Reduced eDreams image. 
- La intercultural is Bronze based on the slides. I will leave it for now, we can change it later?
- Can't find the right way to size logos differently. If anyone has time to give it a go...feel free.

**Comment by JavierCane** [comment]
Good job @immavalls!

We'll add the suggestions as an aside task on Trello in order to let anyone iterate this a little bit more 🙂

**Comment by ignasi35** [comment]
@JavierCane (et al.) some of the tasks above are _low-hanging fruit_ easy to contribute. May I suggest you add them as issues and label them (e.g. `help wanted`) so people passing by (like me) can quickly spot them and work on them?

**Comment by ignasi35** [comment]
done https://github.com/scbcn/scbcn.github.io/issues/37

**Pull request merged**
